name: finsight
description: "Finance + Insight"
publish_to: 'none'
version: 1.0.0+2
environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.0.2
  csv: ^6.0.0
  path_provider: ^2.1.5
  url_launcher: ^6.2.6
  http: ^1.2.2  
  open_file: ^3.5.9
  intl: ^0.19.0
  fl_chart: ^0.69.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  plaid_flutter: ^4.1.1
  google_sign_in: ^6.2.2
  collection: ^1.18.0
  pdf: ^3.11.1
  printing: ^5.13.4
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.2
  syncfusion_flutter_charts: ^29.1.37+1
  timeago: ^3.7.0
  flutter_markdown: ^0.7.7
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  flutter_secure_storage: ^9.0.0
  cloud_firestore: ^5.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  android: true
  ios: true
  color: "#ffffff"
  image: "assets/images/logo_cropped.png"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/data/monthly_spending_categories.csv
    - assets/data/account_balances.csv
    - assets/data/credit_score.csv
    - assets/data/monthly_cashflow.csv
    - assets/data/transactions.csv
    - assets/data/checking_accounts.csv
    - assets/data/credit_cards.csv
    - assets/images/logo.png
    - assets/images/logo_cropped.png
    - assets/images/google_logo.png
    - assets/fonts/Roboto-Regular.ttf
    - assets/images/just_logo.png
    - assets/icon/icon.png