// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqt6zVKSFKiSqO2RT7JESQmDc0nKGwqyI',
    appId: '1:946317225084:web:a4ca32040bfe6cc6532df9',
    messagingSenderId: '946317225084',
    projectId: 'finsight-a5027',
    authDomain: 'finsight-a5027.firebaseapp.com',
    storageBucket: 'finsight-a5027.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSZDGnASb2dk2M4ELcK4oYkBIb6N_gmGo',
    appId: '1:946317225084:android:c280be2f0cc26ea0532df9',
    messagingSenderId: '946317225084',
    projectId: 'finsight-a5027',
    storageBucket: 'finsight-a5027.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN21HLuyTbioRl-LVwiBPnIgkPLgW9DQI',
    appId: '1:946317225084:ios:16e009db05c4bb13532df9',
    messagingSenderId: '946317225084',
    projectId: 'finsight-a5027',
    storageBucket: 'finsight-a5027.firebasestorage.app',
    iosClientId: '946317225084-t8flbvdpepob3sc998vtg8dg3ehab8io.apps.googleusercontent.com',
    iosBundleId: 'com.finsight.finsight',
  );

}